R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
    //Larger Vehicles
	"BRDM2_HQ_Base",
	"BTR40_MG_base_EP1",
	"Landrover_civ",
	"Offroad_02_base_F",
	"Offroad_01_unarmed_base_F",
	"Offroad_01_repair_base_F",
	"LSV_01_base_F",
	"LSV_02_base_F",
	"MRAP_03_base_F",
	"SUV_01_base_F",
	"SUV_armored_Base",
	"SUV_Base",
	"UAZ_Base",
	"HMMWV_Base",
	
	//Trucks
	"Truck_F",	
	"MRAP_01_base_F",
	"MRAP_02_base_F",		
            
    //Armed
    "Offroad_01_military_base_F",
	          
    //Boats
	"Boat_Transport_02_base_F",
	"SDV_01_base_F",
	"Boat_Civil_01_base_F",
	
	//Zat Added
	
	"Exile_Bike_QuadBike_Black",
			"Exile_Bike_QuadBike_Blue",
			"Exile_Bike_QuadBike_Red",
			"Exile_Bike_QuadBike_White",
			"Exile_Bike_QuadBike_Nato",
			"Exile_Bike_QuadBike_Csat",
			"Exile_Bike_QuadBike_Fia",
			"Exile_Bike_QuadBike_Guerilla01",
			"Exile_Bike_QuadBike_Guerilla02",
			"Exile_Car_Kart_BluKing",
			"Exile_Car_Kart_RedStone",
			"Exile_Car_Kart_Vrana",
			"Exile_Car_Kart_Green",
			"Exile_Car_Kart_Blue",
			"Exile_Car_Kart_Orange",
			"Exile_Car_Kart_White",
			"Exile_Car_Kart_Yellow",
			"Exile_Car_Kart_Black",
			"Exile_Car_Hatchback_Beige",
			"Exile_Car_Hatchback_Green",
			"Exile_Car_Hatchback_Blue",
			"Exile_Car_Hatchback_BlueCustom",
			"Exile_Car_Hatchback_BeigeCustom",
			"Exile_Car_Hatchback_Yellow",
			"Exile_Car_Hatchback_Grey",
			"Exile_Car_Hatchback_Black",
			"Exile_Car_Hatchback_Dark",
			"Exile_Car_Hatchback_Rusty1",
			"Exile_Car_Hatchback_Rusty2",
			"Exile_Car_Hatchback_Rusty3",
			"Exile_Car_Golf_Red",
			"Exile_Car_Golf_Black",
			"Exile_Car_Ikarus_Blue",
			"Exile_Car_Ikarus_Red",
			"Exile_Car_Ikarus_Party",
			"Exile_Car_Ural_Open_Blue",
			"Exile_Car_Ural_Open_Yellow",
			"Exile_Car_Ural_Open_Worker",
			"Exile_Car_Ural_Open_Military",
			"CUP_B_Ural_Open_CDF",
			"CUP_B_Ural_Empty_CDF",
			"Exile_Car_Ural_Covered_Blue",
			"Exile_Car_Ural_Covered_Yellow",
			"Exile_Car_Ural_Covered_Worker",
			"Exile_Car_Ural_Covered_Military",
			"CUP_B_MTVR_USA",
			"CUP_B_MTVR_USMC",
			"CUP_B_Ural_CDF",
			"CUP_B_MTVR_Ammo_USA",
			"CUP_B_MTVR_Refuel_USA",
			"CUP_B_MTVR_Repair_USA",
			"CUP_B_MTVR_Ammo_USMC",
			"CUP_B_MTVR_Refuel_USMC",
			"CUP_B_MTVR_Repair_USMC",
			"CUP_B_Ural_Refuel_CDF",
			"CUP_B_Ural_Repair_CDF",
			"CUP_B_Ural_Reammo_CDF",
			"Exile_Car_V3S_Open",
			"Exile_Car_V3S_Covered",
			"Exile_Car_SUVXL_Black",
			"Exile_Car_Tractor_Red",
			"Exile_Car_OldTractor_Red",
			"Exile_Car_TowTractor_White",
			"Exile_Car_Octavius_White",
			"Exile_Car_Octavius_Black",
			"Exile_Car_UAZ_Green",
			"CUP_B_UAZ_Unarmed_CDF",
			"CUP_B_UAZ_Unarmed_ACR",
			"Exile_Car_UAZ_Open_Green",
			"CUP_B_UAZ_Open_ACR",
			"CUP_B_UAZ_Open_CDF",
			"Exile_Car_LandRover_Red",
			"Exile_Car_LandRover_Urban",
			"Exile_Car_LandRover_Green",
			"Exile_Car_LandRover_Sand",
			"Exile_Car_LandRover_Desert",
			"CUP_B_LR_Transport_CZ_W",
			"CUP_B_LR_Transport_CZ_D",
			"CUP_B_LR_Transport_GB_W",
			"CUP_B_LR_Transport_GB_D",
			"Exile_Car_LandRover_Ambulance_Green",
			"Exile_Car_LandRover_Ambulance_Desert",
			"Exile_Car_LandRover_Ambulance_Sand",
			"CUP_B_LR_Ambulance_CZ_W",
			"CUP_B_LR_Ambulance_CZ_D",
			"CUP_B_LR_Ambulance_GB_W",
			"Exile_Car_Lada_Green",
			"Exile_Car_Lada_Taxi",
			"Exile_Car_Lada_Red",
			"Exile_Car_Lada_White",
			"Exile_Car_Lada_Hipster",
			"Exile_Car_Volha_Blue",
			"Exile_Car_Volha_White",
			"Exile_Car_Volha_Black",
			"Exile_Car_Hatchback_Sport_Red",
			"Exile_Car_Hatchback_Sport_Blue",
			"Exile_Car_Hatchback_Sport_Orange",
			"Exile_Car_Hatchback_Sport_White",
			"Exile_Car_Hatchback_Sport_Beige",
			"Exile_Car_Hatchback_Sport_Green",
			"Exile_Car_HEMMT",
			"Exile_Car_Offroad_Red",
			"Exile_Car_Offroad_Beige",
			"Exile_Car_Offroad_White",
			"Exile_Car_Offroad_Blue",
			"Exile_Car_Offroad_DarkRed",
			"Exile_Car_Offroad_BlueCustom",
			"Exile_Car_Offroad_Guerilla01",
			"Exile_Car_Offroad_Guerilla02",
			"Exile_Car_Offroad_Guerilla03",
			"Exile_Car_Offroad_Guerilla04",
			"Exile_Car_Offroad_Guerilla05",
			"Exile_Car_Offroad_Guerilla06",
			"Exile_Car_Offroad_Guerilla07",
			"Exile_Car_Offroad_Guerilla08",
			"Exile_Car_Offroad_Guerilla09",
			"Exile_Car_Offroad_Guerilla10",
			"Exile_Car_Offroad_Guerilla11",
			"Exile_Car_Offroad_Guerilla12",
			"Exile_Car_Offroad_Rusty1",
			"Exile_Car_Offroad_Rusty2",
			"Exile_Car_Offroad_Rusty3",
			"Exile_Car_Offroad_Repair_Civillian",
			"Exile_Car_Offroad_Repair_Red",
			"Exile_Car_Offroad_Repair_Beige",
			"Exile_Car_Offroad_Repair_White",
			"Exile_Car_Offroad_Repair_Blue",
			"Exile_Car_Offroad_Repair_DarkRed",
			"Exile_Car_Offroad_Repair_BlueCustom",
			"Exile_Car_Offroad_Repair_Guerilla01",
			"Exile_Car_Offroad_Repair_Guerilla02",
			"Exile_Car_Offroad_Repair_Guerilla03",
			"Exile_Car_Offroad_Repair_Guerilla04",
			"Exile_Car_Offroad_Repair_Guerilla05",
			"Exile_Car_Offroad_Repair_Guerilla06",
			"Exile_Car_Offroad_Repair_Guerilla07",
			"Exile_Car_Offroad_Repair_Guerilla08",
			"Exile_Car_Offroad_Repair_Guerilla09",
			"Exile_Car_Offroad_Repair_Guerilla10",
			"Exile_Car_Offroad_Repair_Guerilla11",
			"Exile_Car_Offroad_Repair_Guerilla12",
			"Exile_Car_SUV_Red",
			"Exile_Car_SUV_Black",
			"Exile_Car_SUV_Grey",
			"Exile_Car_SUV_Orange",
			"Exile_Car_BTR40_Green",
			"Exile_Car_BTR40_Camo",
			"Exile_Car_HMMWV_MEV_Green",
			"Exile_Car_HMMWV_MEV_Desert",
			"Exile_Car_HMMWV_UNA_Green",
			"Exile_Car_HMMWV_UNA_Desert",
			"CUP_B_HMMWV_Unarmed_USMC",
			"CUP_B_HMMWV_Unarmed_USA",
			"CUP_B_HMMWV_Transport_USA",
			"CUP_B_HMMWV_Terminal_USA",
			"CUP_B_HMMWV_Ambulance_USMC",
			"CUP_B_HMMWV_Ambulance_USA",
			"CUP_B_HMMWV_Ambulance_ACR",
			"Exile_Car_Tempest",
			"Exile_Car_Van_Black",
			"Exile_Car_Van_White",
			"Exile_Car_Van_Red",
			"Exile_Car_Van_Guerilla01",
			"Exile_Car_Van_Guerilla02",
			"Exile_Car_Van_Guerilla03",
			"Exile_Car_Van_Guerilla04",
			"Exile_Car_Van_Guerilla05",
			"Exile_Car_Van_Guerilla06",
			"Exile_Car_Van_Guerilla07",
			"Exile_Car_Van_Guerilla08",
			"Exile_Car_Van_Box_Black",
			"Exile_Car_Van_Box_White",
			"Exile_Car_Van_Box_Red",
			"Exile_Car_Van_Box_Guerilla01",
			"Exile_Car_Van_Box_Guerilla02",
			"Exile_Car_Van_Box_Guerilla03",
			"Exile_Car_Van_Box_Guerilla04",
			"Exile_Car_Van_Box_Guerilla05",
			"Exile_Car_Van_Box_Guerilla06",
			"Exile_Car_Van_Box_Guerilla07",
			"Exile_Car_Van_Box_Guerilla08",
			"Exile_Car_Van_Fuel_Black",
			"Exile_Car_Van_Fuel_White",
			"Exile_Car_Van_Fuel_Red",
			"Exile_Car_Van_Fuel_Guerilla01",
			"Exile_Car_Van_Fuel_Guerilla02",
			"Exile_Car_Van_Fuel_Guerilla03",
			"Exile_Car_Zamak",
			"Exile_Car_ProwlerLight",
			"Exile_Car_ProwlerUnarmed",
			"Exile_Car_QilinUnarmed",
			"Exile_Car_MB4WD",
			"Exile_Car_MB4WDOpen"
	
];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
    //Cars
    "Hatchback_01_base_F",
	"Lada_Base",
	"Octavia_Base",	
	"volha_Base",
    
    //Larger Vehicles
	"BRDM2_HQ_Base",
	"BTR40_MG_base_EP1",
	"Landrover_civ",
	"Offroad_02_base_F",
	"Offroad_01_unarmed_base_F",
	"Offroad_01_repair_base_F",
	"LSV_01_base_F",
	"LSV_02_base_F",
	"MRAP_03_base_F",
	"SUV_01_base_F",
	"SUV_armored_Base",
	"SUV_Base",
	"UAZ_Base",
	"HMMWV_Base",
	
	//Trucks
	"Truck_F",	
	"MRAP_01_base_F",
	"MRAP_02_base_F",		
            
    //Armed
    "Offroad_01_military_base_F",
	          
    //Boats
	"Boat_Transport_02_base_F",
	"SDV_01_base_F",
	"Boat_Civil_01_base_F",
	
	//Zat Added
	
	"Exile_Bike_QuadBike_Black",
			"Exile_Bike_QuadBike_Blue",
			"Exile_Bike_QuadBike_Red",
			"Exile_Bike_QuadBike_White",
			"Exile_Bike_QuadBike_Nato",
			"Exile_Bike_QuadBike_Csat",
			"Exile_Bike_QuadBike_Fia",
			"Exile_Bike_QuadBike_Guerilla01",
			"Exile_Bike_QuadBike_Guerilla02",
			"Exile_Car_Kart_BluKing",
			"Exile_Car_Kart_RedStone",
			"Exile_Car_Kart_Vrana",
			"Exile_Car_Kart_Green",
			"Exile_Car_Kart_Blue",
			"Exile_Car_Kart_Orange",
			"Exile_Car_Kart_White",
			"Exile_Car_Kart_Yellow",
			"Exile_Car_Kart_Black",
			"Exile_Car_Hatchback_Beige",
			"Exile_Car_Hatchback_Green",
			"Exile_Car_Hatchback_Blue",
			"Exile_Car_Hatchback_BlueCustom",
			"Exile_Car_Hatchback_BeigeCustom",
			"Exile_Car_Hatchback_Yellow",
			"Exile_Car_Hatchback_Grey",
			"Exile_Car_Hatchback_Black",
			"Exile_Car_Hatchback_Dark",
			"Exile_Car_Hatchback_Rusty1",
			"Exile_Car_Hatchback_Rusty2",
			"Exile_Car_Hatchback_Rusty3",
			"Exile_Car_Golf_Red",
			"Exile_Car_Golf_Black",
			"Exile_Car_Ikarus_Blue",
			"Exile_Car_Ikarus_Red",
			"Exile_Car_Ikarus_Party",
			"Exile_Car_Ural_Open_Blue",
			"Exile_Car_Ural_Open_Yellow",
			"Exile_Car_Ural_Open_Worker",
			"Exile_Car_Ural_Open_Military",
			"CUP_B_Ural_Open_CDF",
			"CUP_B_Ural_Empty_CDF",
			"Exile_Car_Ural_Covered_Blue",
			"Exile_Car_Ural_Covered_Yellow",
			"Exile_Car_Ural_Covered_Worker",
			"Exile_Car_Ural_Covered_Military",
			"CUP_B_MTVR_USA",
			"CUP_B_MTVR_USMC",
			"CUP_B_Ural_CDF",
			"CUP_B_MTVR_Ammo_USA",
			"CUP_B_MTVR_Refuel_USA",
			"CUP_B_MTVR_Repair_USA",
			"CUP_B_MTVR_Ammo_USMC",
			"CUP_B_MTVR_Refuel_USMC",
			"CUP_B_MTVR_Repair_USMC",
			"CUP_B_Ural_Refuel_CDF",
			"CUP_B_Ural_Repair_CDF",
			"CUP_B_Ural_Reammo_CDF",
			"Exile_Car_V3S_Open",
			"Exile_Car_V3S_Covered",
			"Exile_Car_SUVXL_Black",
			"Exile_Car_Tractor_Red",
			"Exile_Car_OldTractor_Red",
			"Exile_Car_TowTractor_White",
			"Exile_Car_Octavius_White",
			"Exile_Car_Octavius_Black",
			"Exile_Car_UAZ_Green",
			"CUP_B_UAZ_Unarmed_CDF",
			"CUP_B_UAZ_Unarmed_ACR",
			"Exile_Car_UAZ_Open_Green",
			"CUP_B_UAZ_Open_ACR",
			"CUP_B_UAZ_Open_CDF",
			"Exile_Car_LandRover_Red",
			"Exile_Car_LandRover_Urban",
			"Exile_Car_LandRover_Green",
			"Exile_Car_LandRover_Sand",
			"Exile_Car_LandRover_Desert",
			"CUP_B_LR_Transport_CZ_W",
			"CUP_B_LR_Transport_CZ_D",
			"CUP_B_LR_Transport_GB_W",
			"CUP_B_LR_Transport_GB_D",
			"Exile_Car_LandRover_Ambulance_Green",
			"Exile_Car_LandRover_Ambulance_Desert",
			"Exile_Car_LandRover_Ambulance_Sand",
			"CUP_B_LR_Ambulance_CZ_W",
			"CUP_B_LR_Ambulance_CZ_D",
			"CUP_B_LR_Ambulance_GB_W",
			"Exile_Car_Lada_Green",
			"Exile_Car_Lada_Taxi",
			"Exile_Car_Lada_Red",
			"Exile_Car_Lada_White",
			"Exile_Car_Lada_Hipster",
			"Exile_Car_Volha_Blue",
			"Exile_Car_Volha_White",
			"Exile_Car_Volha_Black",
			"Exile_Car_Hatchback_Sport_Red",
			"Exile_Car_Hatchback_Sport_Blue",
			"Exile_Car_Hatchback_Sport_Orange",
			"Exile_Car_Hatchback_Sport_White",
			"Exile_Car_Hatchback_Sport_Beige",
			"Exile_Car_Hatchback_Sport_Green",
			"Exile_Car_HEMMT",
			"Exile_Car_Offroad_Red",
			"Exile_Car_Offroad_Beige",
			"Exile_Car_Offroad_White",
			"Exile_Car_Offroad_Blue",
			"Exile_Car_Offroad_DarkRed",
			"Exile_Car_Offroad_BlueCustom",
			"Exile_Car_Offroad_Guerilla01",
			"Exile_Car_Offroad_Guerilla02",
			"Exile_Car_Offroad_Guerilla03",
			"Exile_Car_Offroad_Guerilla04",
			"Exile_Car_Offroad_Guerilla05",
			"Exile_Car_Offroad_Guerilla06",
			"Exile_Car_Offroad_Guerilla07",
			"Exile_Car_Offroad_Guerilla08",
			"Exile_Car_Offroad_Guerilla09",
			"Exile_Car_Offroad_Guerilla10",
			"Exile_Car_Offroad_Guerilla11",
			"Exile_Car_Offroad_Guerilla12",
			"Exile_Car_Offroad_Rusty1",
			"Exile_Car_Offroad_Rusty2",
			"Exile_Car_Offroad_Rusty3",
			"Exile_Car_Offroad_Repair_Civillian",
			"Exile_Car_Offroad_Repair_Red",
			"Exile_Car_Offroad_Repair_Beige",
			"Exile_Car_Offroad_Repair_White",
			"Exile_Car_Offroad_Repair_Blue",
			"Exile_Car_Offroad_Repair_DarkRed",
			"Exile_Car_Offroad_Repair_BlueCustom",
			"Exile_Car_Offroad_Repair_Guerilla01",
			"Exile_Car_Offroad_Repair_Guerilla02",
			"Exile_Car_Offroad_Repair_Guerilla03",
			"Exile_Car_Offroad_Repair_Guerilla04",
			"Exile_Car_Offroad_Repair_Guerilla05",
			"Exile_Car_Offroad_Repair_Guerilla06",
			"Exile_Car_Offroad_Repair_Guerilla07",
			"Exile_Car_Offroad_Repair_Guerilla08",
			"Exile_Car_Offroad_Repair_Guerilla09",
			"Exile_Car_Offroad_Repair_Guerilla10",
			"Exile_Car_Offroad_Repair_Guerilla11",
			"Exile_Car_Offroad_Repair_Guerilla12",
			"Exile_Car_SUV_Red",
			"Exile_Car_SUV_Black",
			"Exile_Car_SUV_Grey",
			"Exile_Car_SUV_Orange",
			"Exile_Car_BTR40_Green",
			"Exile_Car_BTR40_Camo",
			"Exile_Car_HMMWV_MEV_Green",
			"Exile_Car_HMMWV_MEV_Desert",
			"Exile_Car_HMMWV_UNA_Green",
			"Exile_Car_HMMWV_UNA_Desert",
			"CUP_B_HMMWV_Unarmed_USMC",
			"CUP_B_HMMWV_Unarmed_USA",
			"CUP_B_HMMWV_Transport_USA",
			"CUP_B_HMMWV_Terminal_USA",
			"CUP_B_HMMWV_Ambulance_USMC",
			"CUP_B_HMMWV_Ambulance_USA",
			"CUP_B_HMMWV_Ambulance_ACR",
			"Exile_Car_Tempest",
			"Exile_Car_Van_Black",
			"Exile_Car_Van_White",
			"Exile_Car_Van_Red",
			"Exile_Car_Van_Guerilla01",
			"Exile_Car_Van_Guerilla02",
			"Exile_Car_Van_Guerilla03",
			"Exile_Car_Van_Guerilla04",
			"Exile_Car_Van_Guerilla05",
			"Exile_Car_Van_Guerilla06",
			"Exile_Car_Van_Guerilla07",
			"Exile_Car_Van_Guerilla08",
			"Exile_Car_Van_Box_Black",
			"Exile_Car_Van_Box_White",
			"Exile_Car_Van_Box_Red",
			"Exile_Car_Van_Box_Guerilla01",
			"Exile_Car_Van_Box_Guerilla02",
			"Exile_Car_Van_Box_Guerilla03",
			"Exile_Car_Van_Box_Guerilla04",
			"Exile_Car_Van_Box_Guerilla05",
			"Exile_Car_Van_Box_Guerilla06",
			"Exile_Car_Van_Box_Guerilla07",
			"Exile_Car_Van_Box_Guerilla08",
			"Exile_Car_Van_Fuel_Black",
			"Exile_Car_Van_Fuel_White",
			"Exile_Car_Van_Fuel_Red",
			"Exile_Car_Van_Fuel_Guerilla01",
			"Exile_Car_Van_Fuel_Guerilla02",
			"Exile_Car_Van_Fuel_Guerilla03",
			"Exile_Car_Zamak",
			"Exile_Car_ProwlerLight",
			"Exile_Car_ProwlerUnarmed",
			"Exile_Car_QilinUnarmed",
			"Exile_Car_MB4WD",
			"Exile_Car_MB4WDOpen"
	
                        
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
    
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
    //Cars
    "Hatchback_01_base_F",
	"Lada_Base",
	"Octavia_Base",	
	"volha_Base",
    
    //Larger Vehicles
	"BRDM2_HQ_Base",
	"BTR40_MG_base_EP1",
	"Landrover_civ",
	"Offroad_02_base_F",
	"Offroad_01_unarmed_base_F",
	"Offroad_01_repair_base_F",
	"LSV_01_base_F",
	"LSV_02_base_F",
	"MRAP_03_base_F",
	"SUV_01_base_F",
	"SUV_armored_Base",
	"SUV_Base",
	"UAZ_Base",
	"HMMWV_Base",
	
	//Trucks
	"Truck_F",	
	"MRAP_01_base_F",
	"MRAP_02_base_F",		
            
    //Armed
    "Offroad_01_military_base_F",
	"Tank_F",
	
	          
    //Boats
	"Boat_Transport_02_base_F",
	"SDV_01_base_F",
	"Boat_Civil_01_base_F"             
];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
    //Cars
    ["Hatchback_01_base_F", 10],
	["Lada_Base", 10],
	["Octavia_Base", 10],	
	["volha_Base", 10],
    
    //Larger Vehicles
	["BRDM2_HQ_Base", 25],
	["BTR40_MG_base_EP1", 25],
	["Landrover_civ", 25],
	["Offroad_02_base_F", 25],
	["Offroad_01_unarmed_base_F", 25],
	["Offroad_01_repair_base_F", 25],
	["LSV_01_base_F", 50],
	["LSV_02_base_F", 50],
	["MRAP_03_base_F", 50],
	["SUV_01_base_F", 25],
	["SUV_armored_Base", 25],
	["SUV_Base", 25],
	["UAZ_Base", 25],
	["HMMWV_Base", 25],
	["MRAP_01_base_F", 50],
	["MRAP_02_base_F", 50],
	
	//Trucks
	["Truck_F", 100],				
            
    //Armed
    ["Offroad_01_military_base_F", 25],
	          
    //Boats
	["Boat_Transport_02_base_F", 25],
	["SDV_01_base_F", 25],
	["Boat_Civil_01_base_F", 25]
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
    ["Quadbike_01_base_F", 25],
    ["Bicycle", 10],
	["Golf_Base", 25],   
    ["Kart_01_Base_F", 25],
    ["Tractor_Base", 25],
	["Rubber_duck_base_F", 25],   
    ["TowingTractor", 25]
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
    "Bicycle"
];