// Unarmed Vehicles Matching Prices File. Finished by ZAT 12-8-17

class Unarmed_Ground
	{
		name = "Unarmed Ground";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] = 
		{
			"class Exile_Bike_OldBike",
			"class Exile_Bike_MountainBike",
			"class Exile_Bike_QuadBike_Black",
			"class Exile_Bike_QuadBike_Nato",
			"class Exile_Bike_QuadBike_Csat",
			"class Exile_Bike_QuadBike_Fia",
			"class Exile_Bike_QuadBike_Guerilla01",
			"class Exile_Car_Kart_BluKing",
			"class Exile_Car_Kart_RedStone",
			"class Exile_Car_Kart_Vrana",
			"class Exile_Car_Kart_Green",
			"class Exile_Car_Kart_Blue",
			"class Exile_Car_Kart_Orange",
			"class Exile_Car_Kart_White",
			"class Exile_Car_Kart_Yellow",
			"class Exile_Car_Kart_Black",
			"class Exile_Car_Hatchback_Beige",
			"class Exile_Car_Hatchback_Green",
			"class Exile_Car_Hatchback_Blue",
			"class Exile_Car_Hatchback_BlueCustom",
			"class Exile_Car_Hatchback_BeigeCustom",
			"class Exile_Car_Hatchback_Yellow",
			"class Exile_Car_Hatchback_Grey",
			"class Exile_Car_Hatchback_Black",
			"class Exile_Car_Golf_Red",
			"class Exile_Car_Golf_Black",
			"class Exile_Car_Ikarus_Blue",
			"class Exile_Car_Ikarus_Red",
			"class Exile_Car_Ikarus_Party",
			"class Exile_Car_Ural_Open_Worker",
			"class Exile_Car_Ural_Open_Military",
			"class Exile_Car_Ural_Covered_Worker",
			"class Exile_Car_Ural_Covered_Military",
			"class Exile_Car_V3S_Open",
			"class Exile_Car_V3S_Covered",
			"class Exile_Car_SUVXL_Black",
			"class Exile_Car_Tractor_Red",
			"class Exile_Car_OldTractor_Red",
			"class Exile_Car_TowTractor_White",
			"class Exile_Car_Octavius_White",
			"class Exile_Car_Octavius_Black",
			"class Exile_Car_UAZ_Green",
			"class Exile_Car_UAZ_Open_Green",
			"class Exile_Car_LandRover_Urban",
			"class Exile_Car_LandRover_Green",
			"class Exile_Car_LandRover_Sand",
			"class Exile_Car_LandRover_Desert",
			"class Exile_Car_LandRover_Ambulance_Green",
			"class Exile_Car_Lada_Taxi",
			"class Exile_Car_Lada_White",
			"class Exile_Car_Lada_Hipster",
			"class Exile_Car_Volha_White",
			"class Exile_Car_Volha_Black",
			"class Exile_Car_Hatchback_Sport_Red",
			"class Exile_Car_Hatchback_Sport_Blue",
			"class Exile_Car_Hatchback_Sport_Orange",
			"class Exile_Car_Hatchback_Sport_White",
			"class Exile_Car_Hatchback_Sport_Green",
			"class Exile_Car_HEMMT",
			"class Exile_Car_Offroad_Red",
			"class Exile_Car_Offroad_Beige",
			"class Exile_Car_Offroad_White",
			"class Exile_Car_Offroad_Blue",
			"class Exile_Car_Offroad_DarkRed",
			"class Exile_Car_Offroad_BlueCustom",
			"class Exile_Car_Offroad_Guerilla01",
			"class Exile_Car_Offroad_Guerilla02",
			"class Exile_Car_Offroad_Guerilla05",
			"class Exile_Car_Offroad_Guerilla08",
			"class Exile_Car_Offroad_Guerilla12",
			"class Exile_Car_Offroad_Repair_Civillian",
			"class Exile_Car_Offroad_Repair_Blue",
			"class Exile_Car_Offroad_Repair_DarkRed",
			"class Exile_Car_Offroad_Repair_BlueCustom",
			"class Exile_Car_Offroad_Repair_Guerilla10",
			"class Exile_Car_Offroad_Repair_Guerilla11",
			"class Exile_Car_Offroad_Repair_Guerilla12",
			"class Exile_Car_SUV_Red",
			"class Exile_Car_SUV_Black",
			"class Exile_Car_SUV_Grey",
			"class Exile_Car_SUV_Orange",
			"class Exile_Car_BTR40_MG_Green",
			"class Exile_Car_BTR40_MG_Camo",
			"class Exile_Car_BTR40_Green",
			"class Exile_Car_BTR40_Camo",
			"class Exile_Car_HMMWV_MEV_Green",
			"class Exile_Car_HMMWV_MEV_Desert",
			"class Exile_Car_HMMWV_UNA_Green",
			"class Exile_Car_HMMWV_UNA_Desert",
			"class Exile_Car_Tempest",
			"class Exile_Car_Van_Black",
			"class Exile_Car_Van_White",
			"class Exile_Car_Van_Red",
			"class Exile_Car_Van_Guerilla01",
			"class Exile_Car_Van_Guerilla07",
			"class Exile_Car_Van_Guerilla08",
			"class Exile_Car_Van_Box_Black",
			"class Exile_Car_Van_Box_White",
			"class Exile_Car_Van_Box_Red",
			"class Exile_Car_Van_Box_Guerilla01",
			"class Exile_Car_Van_Box_Guerilla08",
			"class Exile_Car_Van_Fuel_Black",
			"class Exile_Car_Van_Fuel_White",
			"class Exile_Car_Van_Fuel_Red",
			"class Exile_Car_Van_Fuel_Guerilla01",
			"class Exile_Car_Van_Fuel_Guerilla02",
			"class Exile_Car_Van_Fuel_Guerilla03",
			"class Exile_Car_Zamak",
			"class Exile_Car_ProwlerLight",
			"class Exile_Car_ProwlerUnarmed",
			"class Exile_Car_QilinUnarmed",
			"class Exile_Car_MB4WD",
			"class Exile_Car_MB4WDOpen",
			
		};
	};

class Bikes
{
	name = "Bikes";
	icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
	items[] =
	{
		"Exile_Bike_OldBike",
		"Exile_Bike_MountainBike"
	};
};